### ISSUE TITLE
[Bug] The Saw doesn't output anything + Horizontal log doesn't cut...

### ISSUE THREAD

**Issue by Fireztonez** [BetterWithMods/BetterWithMods#852]
Hello,
I test the saw with the latesty version and I see a big problem, nothing is output when trying to cut anything. If the recipe exist, the input disapear, but nothing is dropped...

I make a video of that problem;
https://youtu.be/7EonZWBLuRM

MInecraft: 1.12.2
Better With Mod: 2.1.4-428
Better With Addons : 0.36
Forge: 14.23.2.2654

Fireztonez

**Comment by DaedalusGame** [comment]
fixed in dev

**Comment by Fireztonez** [comment]
The Saw still doesn't work for Horizontal logs in the last Dev Version of BWM (2.1.4-435).

If needed I can give you list of all mod install on the pack I test.

Fireztonez

**Comment by primetoxinz** [comment]
I'm taking a look at this

**Comment by Fireztonez** [comment]
I just test, all logs by Better With Addons doesn't work at all and the Yew from PrimalCore work only if the log is at vertical, like for vanilla wood.

**Comment by Fireztonez** [comment]
That is realy fast!! I will test that now!

**Comment by Fireztonez** [comment]
Perfect, look like 99% is good!!
the only one I see at the moment that always has a problem and does not work in the majority of the senses is "betterwithaddons: log_termite".
